name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # Allows manual testing
  pull_request:  # Test builds on PRs (but skip release step)
jobs:
  build:
    name: Build release binary
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux
            asset_name: my-widget-linux
          - os: macos-latest
            platform: macos
            asset_name: my-widget-macos
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create and compress text file
        run: |
          mkdir -p build
          echo "Hello from ${{ matrix.platform }}!" > build/hello-${{ matrix.platform }}.txt
          echo "Built on: $(date)" >> build/hello-${{ matrix.platform }}.txt
          echo "OS: ${{ matrix.os }}" >> build/hello-${{ matrix.platform }}.txt
          
          # Create tar.gz archive
          tar -czf hello-${{ matrix.platform }}.tar.gz -C build hello-${{ matrix.platform }}.txt

      - name: Upload compressed file
        run: |
          gh release upload ${{ github.event.release.tag_name }} hello-${{ matrix.platform }}.tar.gz
        env:
          GH_TOKEN: ${{ github.token }}
