name: Build Release Assets

on:
  release:
    types: [created]

jobs:
  build-and-upload:
    name: Build and upload release assets
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: macos
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create and compress text file
        run: |
          mkdir -p build
          echo "Hello from ${{ matrix.platform }}!" > build/hello-${{ matrix.platform }}.txt
          echo "Built on: $(date)" >> build/hello-${{ matrix.platform }}.txt
          echo "OS: ${{ matrix.os }}" >> build/hello-${{ matrix.platform }}.txt
          
          # Create tar.gz archive
          tar -czf hello-${{ matrix.platform }}.tar.gz -C build hello-${{ matrix.platform }}.txt

      - name: Verify build artifact
        run: |
          ls -la hello-${{ matrix.platform }}.tar.gz
          if [[ ! -f "hello-${{ matrix.platform }}.tar.gz" ]]; then
            echo "Expected artifact not found!"
            exit 1
          fi

      - name: Upload to release
        env:
          GH_TOKEN: ${{ github.token }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}
          ARTIFACT_PATH: hello-${{ matrix.platform }}.tar.gz
        run: |
          echo "Uploading to release: $RELEASE_TAG"
          gh release upload "$RELEASE_TAG" "$ARTIFACT_PATH"
