name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # Allows manual testing
  pull_request:  # Test builds on PRs (but skip release step)

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: macos
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build for ${{ matrix.platform }}
      run: |
        # Build your project (replace with your build commands)
        mkdir build
        echo "Hello from ${{ matrix.platform }}" > build/app.txt
        
        # Create platform-specific archive
        tar -czf release-${{ matrix.platform }}.tar.gz build/
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-${{ matrix.platform }}
        path: release-${{ matrix.platform }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')  # Only create release on tags
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release-linux/release-linux.tar.gz
          release-macos/release-macos.tar.gz
        draft: true  # Creates draft release for testing
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
